anomaly-benchmarking: added generate-datasets
whizzml/examples pull request #28
Opened 2016-11-07 17:56 UTC by akashenfelter

Here is the working implementation of the ODD paper. I made one minor change from the paper -- this script creates ten replicate datasets instead of 40. Special thanks to @charleslparker, for his resource deletion in the clean-data example.

Of note, I was running into some problems with queueing up too many datasets at once. This was "solved" by using `create-and-wait-dataset` even though I don't need to rely on that resource to continue.  It would be nice to not have to worry about parallelization when writing a whizzml script.

2016-11-08 00:16 UTC, jaor commented
@akashenfelter when you say you were running into problems with queued datasets, was it executing in the server? if so, it'd be a bug in our server side and i'd like to investigate (if it's in the client side, that's a limitation of the client repl and cannot be solve, but the script should *not* use create-and-wait, since it's really meant to run on the server).

2016-11-08 00:17 UTC, jaor commented
(which means that, no matter what, we should remove those create-and-wait from this script)

2016-11-08 01:22 UTC, akashenfelter commented
I got the error `Error computing primitive operation 'create'. Error handling resource (You don't have enough credits available)`. Talking with @petersen-poul, he says that happens if you exceed the parallelization. I'm not sure it's a bug, as such. I can see why we wouldn't want an arbitrarily long queue.

2016-11-08 01:23 UTC, akashenfelter commented
But I would also welcome being able to create as many datasets as I want, and let the server figure out how to make them. :)

2016-11-08 01:47 UTC, whizzmler commented
the server should already being figuring out how to parallelize your
tasks without problems.  the "you don't have enough credits available"
error might be related to the size of your jobs, not the level of
parallelism.  what are your subscription's parameters? (you didn't tell
me if you got the errors through the REPL or in an execution, but i'm
guessing the latter).  if your subscription parameters are fine, then
there's a bug in our server.

2016-11-08 02:47 UTC, akashenfelter commented
With further investigation, the queueing problem was when trying to run the script in the java repl, not as an execution. Everything is fine when run directly as packaged. I'm removing the `-and-wait-`.

2016-11-10 00:06 UTC, jaor requested changes
A few comments in... most of them are just formatting nits.

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/metadata.json
> +  "name": "Generate datasets",
perhaps "Generate benchmarking datasets"?

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/metadata.json
> +  "description": "",
and a one-line summary description?

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/readme.md
> +  uses a batchprediciton to labels each row with the probability of it
typo: batchprediction

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/readme.md
> +- Transforms the dataset into a binary classification using `make-binary`.
perhaps mention that's a library function

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/readme.md
> +  one of four datasets based on this probability. ("Easy" (0, 0.1666),
if the actual label is "easy" i don't think we should capitalize here...

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +     (update ds-id {"fields" (make-map not-preferred (repeat (count not-preferred) {"preferred" true}))})))
i wouldn't filter non-preferred, just mark all of them as preferred unconditionally:

```
(update ds-id
        {"fields" (make-map (keys fields)
                            (repeat (count fields)
                                    {"preferred" true}))})
```

which is, imo, shorter and easier to understand at first glance.  if you insist on filtering, you should probably guard yourself against an empty `not-preferred` list (and break-down that update to keep the 80 cols limit).

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                (keys field)))))
indentation is off, and perhaps a bit confusing you name the fields map `field` instead of `fields`.

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                (keys field)))))
also, this is going to throw an ugly error if the field is not found... perhaps you'll want to check and `raise` a nicer message...

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +;; returns an dataset of only anomalous points and a new field
typo: an -> a

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +        lr-id (create-and-wait-logisticregression {"dataset" ds})
`(create-and-wait-logistic-regression ds)` works just the same and it's a bit shorter

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                                       "output_fields" lr-fields })
you can just use `"all_fields" true`, and then you don't have to wait for the lr and get its input fields, so the whole thing reads:

```
lr-id (create-logisticregression ds)
bp-id (wait (create-batchprediction lr-id ds {"probabilities" true
                                              "output_dataset" true
                                              "all_fields" true}))
```

there i'm just using wait because i like it that way but
create-and-wait-batchprediction would be perfectly fine, and i'm
passing the raw ids.

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +        prob-ds (fetch prob-ds-id)
you'd better wait for this one, the dataset is not guaranteed to be finished when the batch finishes (and fetch, unlike the create functions, won't wait): `(fetch (wait prob-ds-id))`

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +        obj-field (get-id prob-ds "Is Anomaly?")
this "Is Anomaly?" looks like an excellent candidate for a constant defined in the imported library...

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +        difficulty-sorter (lambda (diff-id) (flatline "(segment-label {{diff-id}} \"easy\" 0.133333 \"medium\" 0.333333 \"hard\" 0.5 \"very hard\")"))
line too long.  note that flatline takes multiple strings, so you can nicely format the quoted expression....e.g.:

```
difficulty-sorter (lambda (diff-id)
                    (flatline "(segment-label {{diff-id}}"
                              "               \"easy\" 0.133333"
                              "               \"medium\" 0.33333"
                              "               \"hard\" 0.5"
                              "               \"very hard\")"))
```

again, maybe the category names would be a candidate for constants
defined somwhere, and you could use there things like `{{C-EASY}}`...

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                  "lisp_filter" (flatline "(= (field {{obj-field}}) \"anomalous\")")
indentation looks off here too.  again, you could just `(create-and-wait-dataset prob-ds-id ...`

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +          (map safe-delete [lr-id bp-id prob-ds-id]))
wrong indentation here too: `when` has a body after the check:

```
(when foo
  bar
  baz)
```

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                            (map (lambda (x) (last x)) split-list))
never wrap a function of one argument with a lambda, it's not necessary:

```
(make-map (map head split-list) (map last split-list))
```

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                 (if (contains? split-map level)
indentation

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                     "lisp_filter" (flatline "(= (field {{split-field}}) {{level}})")
indentation...

```
(create-and-wait-dataset {"foo" 3
                          "bar" 4
                          "baz" 5})
```

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +    (for (x ["easy" "medium" "hard" "very hard"]) (split-it x))))
shorter alternative (but your's is fine if you like it better):

```
(map split-it ["easy" "medium" "hard" "very hard"])
```

(if that list of difficulties appears elsewhere, i'd have a variable for it)

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +        bas-id (create-batchanomalyscore {"anomaly" (wait ad-id)
don't need the explicit `wait`, create will automatically wait for you.

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +        id (get-id (fetch score-ds) "score")
`score-ds` needs to be waited for too: `id (get-id (fetch (wait score-ds))` ....

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                                "lisp_filter" score-low
indentation

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                                 "lisp_filter" score-high
indentation

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +          (map safe-delete [ad-id bas-id score-ds]))
indentation

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                                   "k" 1
indentation

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +          (map safe-delete [ano-cl-id]))
indentation

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +              (repeatedly (min 10 (floor (/ availible-rows k)))
indentation

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +        availible-rows (ds "rows")
typo: available

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +    (for (freq [0.001 0.005 0.01 0.05 0.1])
because of the `when` below, the list evaluated in this `for` may contain `false`s as well as dataset ids: i guess you are taking that into account? an alternative would be to `(filter identity ...)` the list here.

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                    "lisp_filter"
indentation (it's a chore to check via github, but these indentation problems are not because you are using tabs, right? we hates tabsseeess :))

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                                                        delete-resources))))
indentation is weird.  if this is a one-legged `if`, use `when` instead.

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                                                      delete-resources)))
`when` instead of `if`

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                     (if x (generate-map x normal-ds))))
`when`

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +          (map safe-delete (flatten [] [binary
indentation

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/make-binary/library.whizzml
> +  (if id (delete id)))
`when`

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/make-binary/library.whizzml
> +;;       (catch e (log-info (str "Error deleting resource " id " ignored")))))
leftover?

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/make-binary/library.whizzml
> +          (map safe-delete [training-id test-id model-id]))
indentation

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/make-binary/library.whizzml
> +          (safe-delete my-eval))
indentation

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/make-binary/metadata.json
> +  "description": "",
a description would be nice, and perhaps a less generic name

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/make-binary/readme.md
> +"Is Anomaly?". "Is Anomaly?" takes the values "normal" or "anomalous"
this is just a matter of taste, but i'd name it simply "anomaly?", and, at any rate, define a variable for use by clients of the library so that they don't have to hardcore the string in their code.  also, if the name ends in a question mark, its values should be "true" and "false" or "yes", "no" by usual conventions.  If the values are going to be the adjectives above, i'd use as field name something like "anomaly degree" or somesuch, but "anomaly?"/"true"/"false" is shorter and easier to remember/use.

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/make-binary/readme.md
> +- Determines whether the dataset is a regression, a classifications
typo: classification

2016-11-10 00:06 UTC, jaor commented on anomaly-benchmarking/metadata.json
> +  "description": "",
missing description

2016-11-11 20:37 UTC, akashenfelter commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +        difficulty-sorter (lambda (diff-id) (flatline "(segment-label {{diff-id}} \"easy\" 0.133333 \"medium\" 0.333333 \"hard\" 0.5 \"very hard\")"))
Multiple strings! This will make formatting so much nicer!

2016-11-11 20:40 UTC, akashenfelter commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                    "lisp_filter"
Sorry about all the indentation errors. It's a combination of me getting used to formatting conventions, and wanting more space as my expressions get longer and longer. I won't let it happen again. At least it's not tabs? :)

2016-11-11 20:43 UTC, akashenfelter commented on anomaly-benchmarking/make-binary/readme.md
> +"Is Anomaly?". "Is Anomaly?" takes the values "normal" or "anomalous"
I changed the name to "instance type". The label is so arbitrary (what is "normal" and "anomalous" depends, among other things, on the order of the rows) it feels too much like lying to call it "anomaly?"/"true".

2016-11-11 20:55 UTC, akashenfelter commented
Got it! If I didn't comment inline above, I've made the suggested change.  Rebased and ready to go.

2016-11-12 02:53 UTC, merged

2016-11-15 18:26 UTC, akashenfelter commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                                       "output_fields" lr-fields })
I've discovered an issue with using "all_fields". When "all_fields" is false, the output dataset has three fields: the old objective field and the two probability fields. When "all_fields" is true, it takes all the fields from the input dataset, including the objective field. So the output dataset ends up with the objective field twice. @jaor, is this expected behavior?

2016-11-15 18:45 UTC, jaor commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                                       "output_fields" lr-fields })
yes, that's expected. in general, in a batch prediction the input
dataset won't contain the objective,  and if it does, its value doesn't
need to be the same as the predicted one, so having it twice makes sense
(one from the input, which is not used, one the predicted value).

2016-11-15 19:06 UTC, akashenfelter commented on anomaly-benchmarking/generate-datasets/script.whizzml
> +                                       "output_fields" lr-fields })
Ah, thanks. Then I will have to carefully remove the predicted value one.

2016-11-15 19:27 UTC, whizzmler commented
> Ah, thanks. Then I will have to carefully remove the predicted value one.

maybe one thing you can do to make that easier is to give it a different
name in the batch prediction request (by default, we use the same name
as the objective)... e.g. something like "predicted species"

2016-11-15 21:42 UTC, akashenfelter commented
That's what I came up with! That made it very easy to add to the "all_but" list.