New script removing contiguous duplicate keys from an input dataset
whizzml/examples pull request #35
Opened 2016-12-16 05:34 UTC by jaor

2016-12-16 21:40 UTC, akashenfelter requested changes
Just a typo. I did try to figure out how to do this with just one filter, but couldn't make anything nearly as elegant as your two dataset solution.

2016-12-16 21:40 UTC, akashenfelter commented on deduplicate/readme.md
> +expression an request a dataset for each filter in succession and
typo: "... expression, request... succession, and... "

2016-12-16 22:01 UTC, whizzmler commented
typo fixed! yes, i also look for a while for a one filter solution but
didn't come up with anything good enough.  the main problem i found is
not having in flatline any way of storing state as we traverse the
dataset, or to referring to previous values of the new fields.  sooner
or later we are going to have the former (the latter is much harder).

2016-12-17 15:09 UTC, akashenfelter approved these changes

2016-12-17 15:19 UTC, merged

2016-12-17 15:20 UTC, akashenfelter commented
Merged!