Models-per-category changes
whizzml/examples pull request #41
Opened 2017-04-25 20:02 UTC by akashenfelter

The changes suggested by Oscar to improve the script before making it public in the gallery

2017-04-25 20:13 UTC, jaor requested changes
an optimization...

2017-04-25 20:13 UTC, jaor commented on model-per-category/create-category-models/script.whizzml
> +                               "name" (str ((fetch origin-id) "name")
this function is called for all categories, always with the same dataset, so re-fetching it all the time is  a bit inefficient: we can make this function take a name argument and compute that name only once just before we loop over `category-dataset` below...

2017-05-02 20:32 UTC, akashenfelter commented
Sorry this fell off my radar. Nit picked!

2017-05-02 21:48 UTC, jaor requested changes
i think there's a problem...

2017-05-02 21:48 UTC, jaor commented on model-per-category/create-category-models/script.whizzml
> +        name ((fetch dataset) "name")
i don't think that's right: your `name` here is shadowing the `name` returned by `(categories ..)`

2017-05-03 00:58 UTC, akashenfelter commented
Better?

2017-05-03 01:22 UTC, whizzmler commented
no, i'm afraid not :) you changed the name at the wrong place, it's in
the let before calling category-dataset that it must be changed... we
had:

```clojure
(let ([cs missings id name] (categories dataset field)
      ps ...
  <code that, presumable uses `name` above>))
```

and then you added

```clojure
(let ([cs missings id name] (categories dataset field)
      name ((fetch dataset) "name") ;; <-- this name is shadowing the name in pthe previous line
      ps ...
  <code that, presumable uses `name` above, but now `name` is different>))
```

(the name of the parameter can be `name`, there's no shading there).


-- 
No, no, you're not thinking, you're just being logical.
 -Niels Bohr, physicist (1885-1962)

2017-05-03 15:24 UTC, akashenfelter commented
Sorry, I wasn't thinking.

2017-05-03 16:44 UTC, merged