Fixes the possibility that datasets are not finished in split-it befo…
whizzml/examples pull request #46
Opened 2017-06-25 01:23 UTC by petersen-poul

…re subsequently reading the number of rows in sample-it, which can result in a divide by zero error

2017-06-25 01:40 UTC, petersen-poul commented
Actually, hold off on this. I want to add a little improvement.

2017-06-25 04:21 UTC, petersen-poul commented
All done...

2017-06-26 01:34 UTC, jaor commented
@akashenfelter i just assigned the review to you, since i think you are the original author of this script.  please let me know if you don't have the bandwidth and i'll do the review myself.

@petersen-poul i'll nonetheless start the review by observing that this script has tests, so if you've added new functionality, it'd be nice to exercise it in the tests.

2017-06-26 16:32 UTC, akashenfelter requested changes
Everything looks great, this is a nice improvement. One typo, and I agree with jao adding a test of the weighted sampling would be smart.

2017-06-26 16:32 UTC, akashenfelter commented on stratified-sampling/readme.md
> +  instances upto the maximum of the smallest weighted class.
missing space between 'up' and 'to'

2017-06-26 23:35 UTC, akashenfelter commented
Looks good, merging.

2017-06-26 23:37 UTC, merged