Bulk move of previously selected resources to a Project
whizzml/examples pull request #78
Opened 2019-08-07 14:51 UTC by mmerce

2019-08-07 16:00 UTC, jaor requested changes

2019-08-07 16:00 UTC, jaor commented on bulk-move/metadata.json
> +  "kind": "script",
typo: lected. (and perhaps Project -> project)

2019-08-07 16:00 UTC, jaor commented on bulk-move/metadata.json
> +     },
i would instead set `default` to "Unknown" (as a plus, no explanation will be needed in the docstring then)

2019-08-07 16:00 UTC, jaor commented on bulk-move/metadata.json
> +          "name": "project-id",
perhaps "source-id" to mirror "destination-id"? (or source-project/destination-project)

2019-08-07 16:00 UTC, jaor commented on bulk-move/script.whizzml
> +(define RES_LISTERS {"fusion" list-fusions
i forgot: isn't the convention "RES-LISTERS"?

2019-08-07 16:00 UTC, jaor commented on bulk-move/script.whizzml
> +                     "library" list-libraries})
are you sure we need this? there's the standard procedure `resources`, and, for instance `(resources "anomaly" x)` is equivalent to `(list-anomalies x)`...

2019-08-07 16:00 UTC, jaor commented on bulk-move/script.whizzml
> +      (filter (lambda (x) (procedure? x))
`(filter procedure? (for ..))`

2019-08-07 16:00 UTC, jaor commented on bulk-move/metadata.json
> +     },
oh, and in our next release (coming soon) that can be type "project-id" with a default that is not a project-id, so i'ld go for it right away.

2019-08-07 16:00 UTC, jaor commented on bulk-move/metadata.json
> +          "type": "string",
and, as before, we can use here "project-id"

2019-08-07 16:00 UTC, jaor commented on bulk-move/script.whizzml
> +    (catch e (raise "Please, check the project ID")))
`check-project-id` never raises an error, so this seems equivalent to the sorter:

```whizzml
(or (check-project-id project-id)
    (raise "Please, check the project ID"))
```

2019-08-07 16:00 UTC, jaor commented on bulk-move/script.whizzml
> +    (catch e (raise "Please, check the destination project ID")))
same here, no need for try/catch

2019-08-07 16:00 UTC, jaor commented on bulk-move/script.whizzml
> +        (log-info ids)
not sure, but maybe we could log also for non-dry runs, no?

2019-08-07 18:34 UTC, mmerce commented on bulk-move/metadata.json
> +  "kind": "script",
done

2019-08-07 18:36 UTC, mmerce commented on bulk-move/metadata.json
> +     },
I wanted it to be usable just in case we share with the customer. He seems to prefer using the dashboard and that might take a while.

2019-08-07 18:36 UTC, mmerce commented on bulk-move/metadata.json
> +          "name": "project-id",
source-id could mislead, right? better source-project and destination-project

2019-08-07 18:37 UTC, mmerce commented on bulk-move/script.whizzml
> +(define RES_LISTERS {"fusion" list-fusions
I was doubting too, and I guess we've used both but we can decide that is - also for constants.

2019-08-07 18:37 UTC, mmerce commented on bulk-move/script.whizzml
> +                     "library" list-libraries})
Oh, I did not know! Sure it's better to use (resources ...)

2019-08-07 18:38 UTC, mmerce commented on bulk-move/script.whizzml
> +      (filter (lambda (x) (procedure? x))
right

2019-08-07 18:39 UTC, mmerce commented on bulk-move/script.whizzml
> +    (catch e (raise "Please, check the project ID")))
Oh, I thought it did when the project was not an ID.

2019-08-07 18:39 UTC, mmerce commented on bulk-move/script.whizzml
> +        (log-info ids)
I do log the summary part.

2019-08-12 18:45 UTC, mmerce commented
I think I added most suggestions. Please, let me know if anything is missing.

2019-09-10 02:13 UTC, jaor approved these changes

2019-09-10 02:13 UTC, merged