Update AutoML docs to show installation from dashboard
whizzml/examples pull request #88
Opened 2019-12-05 13:00 UTC by unmonoqueteclea

Since yesterday, BigML Dashboard allows the creation (and import) of WhizzML scripts with optional resource input parameters, so now AutoML can be installed fully from the dashboard. It was something requested by some users.

2019-12-10 16:28 UTC, unmonoqueteclea commented
@mmerce I added a new feature that you requested me some time ago. If the user doesn't provide a validation-dataset, AutoML will create one from the training dataset. This is configurable with a new parameter in the configuration.

2019-12-11 08:51 UTC, unmonoqueteclea commented
Last thing in this PR, I promise, I added a new configuration parameter `balance-objective` for ensembles created during feature selection step

2019-12-17 13:12 UTC, unmonoqueteclea commented
@mmerce ping

2019-12-17 22:33 UTC, mmerce requested changes

2019-12-17 22:33 UTC, mmerce commented on automl/readme.md
> +In that case, you will have to find, in the selector, the library you
In that case, import the library that you created in the previous step by selecting it with the drop down selector.

2019-12-17 22:33 UTC, mmerce commented on automl/readme.md
> +After these steps, you will be able to import the script correctly into your
Following these steps, you should be able to create the script in your BigML account.

2019-12-17 22:33 UTC, mmerce commented on automl/readme.md
> +That will create all necessary library and script resources for you.
That will create both the AutoML library and script resources for you.

2019-12-19 15:48 UTC, unmonoqueteclea commented
Ready...

2019-12-20 14:11 UTC, mmerce approved these changes

2019-12-23 15:43 UTC, merged