New script: Statistical Tests
whizzml/examples pull request #94
Opened 2020-02-28 16:43 UTC by unmonoqueteclea

Although it is offered via API, statistical tests can't be created from the Dashboard so it could be interesting having this script that creates them, and show the results nicely. It also creates a Dataset with the results, so they can be shown and analyzed within BigML Dashboard.

2020-02-28 20:31 UTC, mmerce requested changes

2020-02-28 20:31 UTC, mmerce commented on statistical-tests/script.whizzml
> +;; deviations ac
ac?

2020-02-28 20:31 UTC, mmerce commented on statistical-tests/script.whizzml
> +;; the metrics from one of them removing unnecesary keys and
from/for?

2020-02-28 20:31 UTC, mmerce commented on statistical-tests/script.whizzml
> +  (let (test-results ((first-match-key (test type)  "name" subtype) "result"))
double space

2020-02-28 20:31 UTC, mmerce commented on statistical-tests/script.whizzml
> +(define output (statistical-tests))
it will work just as well, but wouldn't it be better to define dataset-id as an input parameter of the procedure?

2020-02-28 20:31 UTC, mmerce commented on statistical-tests/script.whizzml
> +(define (create-source-data)
benford should be an arg for the procedure

2020-02-28 20:31 UTC, mmerce commented on statistical-tests/script.whizzml
> +(define (create-output-dataset)
dataset-id should be an arg

2020-02-28 20:31 UTC, mmerce commented on statistical-tests/script.whizzml
> +  (join ","  (flatten (map (lambda (test name)
double space

2020-03-02 08:25 UTC, unmonoqueteclea commented
Fixed!

2020-03-17 17:03 UTC, unmonoqueteclea commented
Ping @mmerce, I have another pending PR, if would be great if we can merge this one before

2020-03-17 17:35 UTC, mmerce approved these changes

2020-03-17 17:46 UTC, merged